dbt_healthcare:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: '../data/gold/healthcare.duckdb'
      extensions:
        - parquet
        - icu
      settings:
        preserve_insertion_order: false
